version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minimarket_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio-data:/data

volumes:
  db_data:
